version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_for_pingankou
    ports:
      - "1234:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456   # 可根据需要修改密码
      MYSQL_DATABASE: my_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_root_remote.sql:/docker-entrypoint-initdb.d/init_root_remote.sql

volumes:
  mysql-data: